
// This file has been generated by the GUI designer. Do not modify.

public partial class UI
{
	private Gtk.VBox vbox1;

	private Gtk.HBox hbox1;

	private Gtk.Label label2;

	private Gtk.FileChooserButton ofd_select_vcard;

	private Gtk.HBox hbox2;

	private Gtk.Label label4;

	private Gtk.TextView txt_search;

	private Gtk.ScrolledWindow GtkScrolledWindow;

	private Gtk.NodeView dgv_contacts;

	protected virtual void Build()
	{
		Stetic.Gui.Initialize(this);
		// Widget UI
		Name = "UI";
		Title = Mono.Unix.Catalog.GetString("vCardLib UI 1.4");
		Icon = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "./vcard.jpg"));
		WindowPosition = ((Gtk.WindowPosition)(4));
		Gravity = ((Gdk.Gravity)(5));
		// Container child UI.Gtk.Container+ContainerChild
		vbox1 = new Gtk.VBox();
		vbox1.Name = "vbox1";
		vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		hbox1 = new Gtk.HBox();
		hbox1.Name = "hbox1";
		hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		label2 = new Gtk.Label();
		label2.Name = "label2";
		label2.LabelProp = Mono.Unix.Catalog.GetString("File Path:");
		hbox1.Add(label2);
		Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(hbox1[label2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		ofd_select_vcard = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select a File"), ((Gtk.FileChooserAction)(0)));
		ofd_select_vcard.Name = "ofd_select_vcard";
		hbox1.Add(ofd_select_vcard);
		Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(hbox1[ofd_select_vcard]));
		w2.PackType = ((Gtk.PackType)(1));
		w2.Position = 1;
		vbox1.Add(hbox1);
		Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(vbox1[hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		hbox2 = new Gtk.HBox();
		hbox2.Name = "hbox2";
		hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		label4 = new Gtk.Label();
		label4.Name = "label4";
		label4.LabelProp = Mono.Unix.Catalog.GetString("Search:");
		hbox2.Add(label4);
		Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(hbox2[label4]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		txt_search = new Gtk.TextView();
		txt_search.CanFocus = true;
		txt_search.Name = "txt_search";
		txt_search.AcceptsTab = false;
		hbox2.Add(txt_search);
		Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(hbox2[txt_search]));
		w5.Position = 1;
		vbox1.Add(hbox2);
		Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(vbox1[hbox2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		GtkScrolledWindow = new Gtk.ScrolledWindow();
		GtkScrolledWindow.Name = "GtkScrolledWindow";
		GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		dgv_contacts = new Gtk.NodeView();
		dgv_contacts.CanFocus = true;
		dgv_contacts.Name = "dgv_contacts";
		GtkScrolledWindow.Add(dgv_contacts);
		vbox1.Add(GtkScrolledWindow);
		Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(vbox1[GtkScrolledWindow]));
		w8.Position = 2;
		Add(vbox1);
		if ((Child != null))
		{
			Child.ShowAll();
		}
		DefaultWidth = 666;
		DefaultHeight = 432;
		Show();
		DeleteEvent += OnDeleteEvent;
		ofd_select_vcard.SelectionChanged += OnOfdSelectVcardSelectionChanged;
	}
}
